### ISSUE TITLE
Warning: Invalid argument supplied to oneOfType. Expected an array of check functions, but received undefined at index 2.

### ISSUE THREAD

**Issue by sunb123** [agiletechvn/react-native-search-box#46]
Using prop-types@15.5.10
This package doesn't recognize "PropTypes.style" such as in line 501 of index.js
`  cancelButtonStyle: PropTypes.oneOfType([PropTypes.number, PropTypes.object, PropTypes.style]),
`

What is the problem here?

**Comment by kacgrzes** [comment]
It seems like yarn is caching packages by version number, and the last change made [here](https://github.com/agiletechvn/react-native-search-box/commit/2801cdd11b516cbbb48f137a70d051ad959d677b) to fix PropTypes was not cached due to lack of version bumping.

Quickfix:
`"react-native-search-box": "https://github.com/agiletechvn/react-native-search-box"` in `package.json`

More proper way:
@anhtuank7c Bump version number to `0.0.14`
